
addons:
  apt:
    packages:
    - aria2
#before_install:
branches:
  only:
  - develop
  - master

dist: trusty
env:
  global:
  - IMAGE_TAG_LATEST=11.0.2-alpine-3.9
  matrix:
  - IMAGE_ARG_JAVA11_VERSION=11.0.2 IMAGE_ARG_JAVA11_PACKAGE_DIGEST=eba6b1ee7302a7e509a9f28ed4fa2359e29431aed8dcc43b1145a8c8a3847791 IMAGE_ARG_JAVA11_ZULU_VERSION=11.29.3

group: edge
#install: true

#before_script:
script:
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- bash build.sh
- kill %1
#after_script:

services:
- docker
sudo: required
