
version: '2.1'
services:
  #docker-compose build image
  image:
    build:
      context: image
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_FILESERVER=${IMAGE_ARG_FILESERVER}
      #- IMAGE_ARG_FILESERVER=${IMAGE_ARG_FILESERVER:-http://fileserver.infra.top}
      - IMAGE_ARG_JAVA11_VERSION=${IMAGE_ARG_JAVA11_VERSION:-11.0.2}
      - IMAGE_ARG_JAVA11_PACKAGE_DIGEST=${IMAGE_ARG_JAVA11_PACKAGE_DIGEST:-eba6b1ee7302a7e509a9f28ed4fa2359e29431aed8dcc43b1145a8c8a3847791}
      - IMAGE_ARG_JAVA11_ZULU_VERSION=${IMAGE_ARG_JAVA11_ZULU_VERSION:-11.29.3}
    image: ${IMAGE_PREFIX:-cirepo/}${IMAGE_NAME:-java-11-zulu}:${IMAGE_TAG:-11.0.2-alpine-3.9}
  #docker-compose build dumper
  dumper:
    build:
      context: dumper
      dockerfile: Dockerfile_dumper
    image: tmp/dumper:latest
  #docker-compose build archive
  archive:
    build:
      context: .
      dockerfile: Dockerfile_archive
    image: ${IMAGE_PREFIX:-cirepo/}${IMAGE_NAME:-java-11-zulu}:${IMAGE_TAG:-11.0.2-alpine-3.9}-archive
